name: Publish to npm

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ~~~~~~~~~~~~~ Node.js setup ~~~~~~~~~~~~~
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Adjust to match your project's Node version
          registry-url: 'https://registry.npmjs.org/'

      - name: Display Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      # ~~~~~~~~~~~~~ Build project (if needed) ~~~~~~~~~~~~~
      - name: Build project
        run: npm run build # Skip or replace this if not needed

      # ~~~~~~~~~~~~~ Publish to npm ~~~~~~~~~~~~~
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
