name: Create GitHub Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ~~~~~~~~~~~~~ Node.js setup ~~~~~~~~~~~~~
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Adjust to your preferred Node.js version
          cache: 'npm'

      - name: Display Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      # ~~~~~~~~~~~~~ Package asset (optional) ~~~~~~~~~~~~~
      # Adjust this step to package whatever release artifact you want
      - name: Prepare release asset
        run: |
          mkdir -p pkg
          npm pack
          mv *.tgz pkg/tdl-client-node.tgz

      # ~~~~~~~~~~~~~ Create GitHub Release ~~~~~~~~~~~~~
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pkg/tdl-client-node.tgz
